### ISSUE TITLE
Sojurn 2.1.0.4 keeps crashing 

### ISSUE THREAD

**Issue by jgarbi** [kelias/Jarloo.Sojurn#10]
Hi Kelias, 

The problem is back and has been for a little while. It's exactly as before, on at least the 2 computers I use regularly. If I don't update once a day, it crashes. And even when I do update once every day, it crashes very often.I have to start the Update All Shows, and before it finishes, I exit the application. Then I restart the application and most shows have been updated to Today and I can start an Update All Shows and it works fine without crashing.
Tell me what you need and I'll send you everything. And maybe send me your email address so I can send you the json file.

And thanks

Take care,

Jacques Garbi

**Comment by jgarbi** [comment]
[index.txt](https://github.com/kelias/Jarloo.Sojurn/files/816660/index.txt)

It's really the index.json file but I wasn't allowed to upload a json file so I renamed it in .txt

**Comment by kelias** [comment]
I've had the same issue. The threading with Caliburn in the mix is causing issues. I'm in the process of rewriting it to remove MEF and Caliburn and increase the speed. Drives me crazy how long it takes to start up. The majority of that time is spent fetching episode images, which are rarely viewed. 

To avoid that I changed the main window to have the shows but not episodes. Episode images will be loaded when requested instead of immediately. (see the screenshot for an example of how it sits right now)
![sojurn2](https://cloud.githubusercontent.com/assets/536249/23687966/953dd78c-036e-11e7-84aa-a21933ece0e2.png)

Will prob have it so you click on a show and the seasons/episodes show up in a separate window or popup. 

But the good part is it doesn't crash and loads much much faster. (almost instantly on my comp)

Not sure about you but I tend to spend most of my time in the the backlog and timeline and rarely access the episodes. Seems better to front the shows, timeline and backlog and have the episode images load when requested instead of load every time it opens even if you don't look or use them.

**Comment by jgarbi** [comment]
Hi Elias,

Thanks for your mail. I think you have something there. Personally I only use the backlog, not the timeline since I don't watch the shows on TV (being in Switzerland without a connection to US channels). It'd be really great if there were an option somewhere to enable/disable the timeline.
As for the rest, I agree with you that it'd be great to only list the shows without the episodes, and then click on a specific show to display its episodes.
Can you tell me when you've uploaded the new sources ?

Thanks for everything

Jacques garbi    Ceo, colombus sa
+41 21 661 1675 (office) | +41 79 210 5076 (mobile) | www.colombus.com<http://www.colombus.com>


Un service sur mesure et de qualité

________________________________
De : Kelly Elias [notifications@github.com]
Envoyé : mercredi 8 mars 2017 03:51
À : kelias/Jarloo.Sojurn
Cc : Jacques Garbi; Author
Objet : [SPAM] - Re: [kelias/Jarloo.Sojurn] Sojurn 2.1.0.4 keeps crashing (#10) - Email has different SMTP TO: and MIME TO: fields in the email addresses


I've had the same issue. The threading with Caliburn in the mix is causing issues. I'm in the process of rewriting it to remove MEF and Caliburn and increase the speed. Drives me crazy how long it takes to start up. The majority of that time is spent fetching episode images, which are rarely viewed.

To avoid that I changed the main window to have the shows but not episodes. Episode images will be loaded when requested instead of immediately. (see the screenshot for an example of how it sits right now)
[sojurn2]<https://cloud.githubusercontent.com/assets/536249/23687966/953dd78c-036e-11e7-84aa-a21933ece0e2.png>

Will prob have it so you click on a show and the seasons/episodes show up in a separate window or popup.

But the good part is it doesn't crash and loads much much faster. (almost instantly on my comp)

Not sure about you but I tend to spend most of my time in the the backlog and timeline and rarely access the episodes. Seems better to front the shows, timeline and backlog and have the episode images load when requested instead of load every time it opens even if you don't look or use them.

**Comment by kelias** [comment]
The new code is up as branch 2.0. Still hammering out a few bugs but it works better than the master branch currently. All you need to do is grab the code and put your index.json file into the bin folder just like the other. The format of the index. json has not changed.

I will probably merge it into the master in the next few days, have a bit more to do first.

Also your idea of turning off things like the backlog or timeline is a good one. I have been planning on making a settings window for a long time. (since I made the project) The UserSettings class is already there to handle it, just need to plan it out. 

Should also be able to control the directory where the data and images are stored. That way if you use dropbox, Google Drive or any other cloud sync program your info can be put into the cloud so you can share across multiple computers.

**Comment by jgarbi** [comment]
Much much better. And incredibly faster. Well done ! Thanks


Jacques garbi     Ceo, colombus sa
+41 21 661 1675 (office)  |  +41 79 210 5076 (mobile)  |  www.colombus.com<http://www.colombus.com/>



Un service sur mesure et de qualité

**Comment by jgarbi** [comment]
Except one thing you should bring back (and include in the settings window so we can change its settings) it was the ability to launch the episode in streaming directly from the backlog


Jacques garbi     Ceo, colombus sa
+41 21 661 1675 (office)  |  +41 79 210 5076 (mobile)  |  www.colombus.com<http://www.colombus.com/>



Un service sur mesure et de qualité

**Comment by kelias** [comment]
Yeah I will, but I didn't like that it only had a single source. Was thinking about incorporating more of them, so you can pick from a list of sources.

**Comment by jgarbi** [comment]
It'd be great. Looking forward to seeing this.

Jacques garbi    Ceo, colombus sa
+41 21 661 1675 (office) | +41 79 210 5076 (mobile) | www.colombus.com<http://www.colombus.com>


Un service sur mesure et de qualité

________________________________
De : Kelly Elias [notifications@github.com]
Envoyé : samedi 11 mars 2017 23:23
À : kelias/Jarloo.Sojurn
Cc : Jacques Garbi; Author
Objet : [SPAM] - Re: [kelias/Jarloo.Sojurn] Sojurn 2.1.0.4 keeps crashing (#10) - Email has different SMTP TO: and MIME TO: fields in the email addresses


Yeah I will, but I didn't like that it only had a single source. Was thinking about incorporating more of them, so you can pick from a list of sources.

**Comment by jgarbi** [comment]
It should also store its position and size each time otherwise you have to resize the window each time you launch the app.


Jacques garbi     Ceo, colombus sa
+41 21 661 1675 (office)  |  +41 79 210 5076 (mobile)  |  www.colombus.com<http://www.colombus.com/>



Un service sur mesure et de qualité

**Comment by kelias** [comment]
Rl issues, but I have the framework mostly there. If you click it displays a popup (ugly popup for now) but I need to have that launch the provider. Just slammed at work atm. Hopefully soon.

**Comment by kelias** [comment]
v2.0 Has working stream providers now. They are controlled via a new settings file called StreamProviders.json. It has replaceable params to allow for show, season. and episode markers in the URL.

There are 3 atm. ProjectFreeTv, PutLocker, and WatchSeries. (want to add others but many have custom id's etc..) 

Anyway should work for your needs. Should be cutting 2.0 into the master soon.

**Comment by kelias** [comment]
ok 2.0 has been merged into the master. I'm closing this ticket. If you find any issues feel free to make another ticket.
